name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'
  GO_VERSION: '1.21'
  PNPM_VERSION: '8'

jobs:
  # Frontend Testing
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install --no-frozen-lockfile

      - name: Type check
        run: |
          cd frontend
          pnpm run type-check

      - name: Lint
        run: |
          cd frontend
          pnpm run lint

      - name: Run tests
        run: |
          cd frontend
          pnpm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./frontend/coverage

  # Backend Testing
  backend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway]
    env:
      FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: |
          if [ -d "services/${{ matrix.service }}" ]; then
            cd services/${{ matrix.service }}
            go mod tidy
            go mod download
            go test -v -cover ./...
          fi

  # Integration Testing (placeholder for future services)
  integration-test:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Skip integration tests
        run: echo "Skipping integration tests - no additional services implemented yet"

  # Build (on main branch)
  deploy:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test, integration-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
      FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file for Docker build
        run: |
          echo "FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}" > .env

      - name: Build services
        run: |
          docker compose build

      - name: Deploy to staging
        run: |
          echo "Deploy to staging environment - configure when ready"